
{
  "organization": "Azure-Samples",
  "after": "Y3Vyc29yOjM=",
  "pageSize": 3
}

query OrgReposMegaInfoExample($organization:String!, $pageSize: Int) {
  organization(login:$organization){
    repositories (first: $pageSize){
      totalCount
      pageInfo {
        startCursor
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          repositoryName:name name
          id
            url
            descriptionHTML
            stargazers {
              totalCount
            }
            forks {
              totalCount
            }
            issues(states:[OPEN]) {
              totalCount
            }
            pullRequests(states:[OPEN]) {
              totalCount
            }
            updatedAt
        }
      }
    }
  }
}