{
    repository(owner: "facebook", name: "graphql"){
        issues(first:10){
            nodes{
                title
                createdAt
                author{
                    login
                }
            }
        }
    }
}